version: 2.1

jobs:
  infracost:
    # Always use the latest 0.10.x version to pick up bug fixes and new resources.
    # See https://www.infracost.io/docs/integrations/cicd/#docker-images for other options
    docker:
      - image: infracost/infracost:ci-0.10.0-beta.1
    environment:
      TF_ROOT: terraform
    steps:
      - run:
          name: Skip if not pull request
          command: |
            if [ "$CIRCLE_PULL_REQUEST" == "" ]; then
              circleci step halt
            fi
      - attach_workspace:
          at: /tmp
      - checkout
      # Clone the base branch of the pull request (e.g. main/master) into a temp directory.
      - run:
          name: Checkout base branch
          command: git clone $CIRCLE_REPOSITORY_URL --branch=master --single-branch /tmp/base
      # Generate Infracost JSON file as the baseline.
      - run:
          name: Generate Infracost cost estimate baseline
          command: |
              infracost breakdown --path=${TF_ROOT} \
                                  --format=json \
                                  --out-file=/tmp/infracost-base.json
      # Generate an Infracost diff and save it to a JSON file.
      - run:
          name: Generate Infracost cost estimate baseline
          command: |
              infracost diff --path=${TF_ROOT} \
                             --format=json \
                             --compare-to=/tmp/infracost-base.json \
                             --out-file=/tmp/infracost.json
      # Posts a comment to the PR using the 'update' behavior.
      # This creates a single comment and updates it. The "quietest" option.
      # The other valid behaviors are:
      #   delete-and-new - Delete previous comments and create a new one.
      #   hide-and-new - Minimize previous comments and create a new one.
      #   new - Create a new cost estimate comment on every push.
      # See https://www.infracost.io/docs/features/cli_commands/#comment-on-pull-requests for other options.
      - run:
          name: Post Infracost comment
          command: |
              # Extract the PR number from the PR URL
              PULL_REQUEST_NUMBER=${CIRCLE_PULL_REQUEST##*/}
              infracost comment github --path=/tmp/infracost.json \
                                       --repo=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
                                       --pull-request=$PULL_REQUEST_NUMBER \
                                       --github-token=$GITHUB_TOKEN \
                                       --behavior=update
workflows:
  infracost:
    jobs:
      - infracost
