version: 2.1

jobs:
  infracost:
    working_directory: terraform
    docker:
      - image: infracost/infracost:ci-latest
    steps:
      - run:
          name: Skip if not pull request
          command: |
            if [ "$CIRCLE_PULL_REQUEST" == "" ]; then
              circleci step halt
            fi
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: Download Infracost binary
          command: |
            curl -o /tmp/infracost https://infracost-public-dumps.s3.amazonaws.com/builds/ci/infracost-linux-amd64
            chmod +x /tmp/infracost
      - run:
          name: Run Infracost breakdown
          command: |
            /tmp/infracost breakdown --path terraform --format json --out-file infracost.json
      - run:
          name: Test meta
          command: |
             jq ".projects[].metadata" /tmp/infracost-base.json
workflows:
  infracost:
    jobs:
      - terraform_plan
      - infracost:
          requires:
            - terraform_plan
