version: 2.1

jobs:
  terraform_plan:
    docker:
      - image: hashicorp/terraform:latest
    environment:
      TF_ROOT: terraform # If your Terraform is in a subdirectory, specify it here
    steps:
      - checkout
      - run:
          name: Run terraform plan
          command: |
            # IMPORTANT: add any required steps here to setup cloud credentials so Terraform can run
            cd $TF_ROOT
            terraform init
            terraform plan -out tfplan.binary
            terraform show -json tfplan.binary > /tmp/plan.json
      - persist_to_workspace:
          root: /tmp
          paths:
            - plan.json
  infracost:
    working_directory: terraform
    docker:
      - image: infracost/infracost:ci-latest
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: Run Infracost breakdown
          command: |
            # Generate Infracost JSON output, the following docs might be useful:
            # Multi-project/workspaces: https://www.infracost.io/docs/features/config_file
            # Combine Infracost JSON files: https://www.infracost.io/docs/features/cli_commands/#combined-output-formats
            infracost breakdown --path /tmp/plan.json --usage-file infracost-usage.yml --format json --out-file infracost.json
      - run:
          name: Run Infracost comment
          command: |
            # See the 'Comment options' section in our README below for other options.
            PULL_REQUEST_NUMBER=${CIRCLE_PULL_REQUEST##*/} # Extract the PR number from the PR URL
            infracost comment github --path infracost.json --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME --pull-request $PULL_REQUEST_NUMBER --github-token $GITHUB_TOKEN

workflows:
  infracost:
    jobs:
      - terraform_plan
      - infracost:
          requires:
            - terraform_plan
