version: 2.1
orbs:
  infracost: infracost/infracost@0.6.0
  terraform: circleci/terraform@2.0.0
workflows:
  main:
    jobs:
      single-job-lifecycle:
        executor: terraform/default
        steps:
          - checkout
          - terraform/init:
              path: terraform
          - terraform/plan:
              path: terraform
          - command: plan -out .terraform/terraform.tfplan
          - command: show -json .terraform/terraform.tfplan > tfplan.json
        - persist_to_workspace:
            root: /workspace/.terraform
            paths:
              - terraform.tfplan
              - tfplan.json
      # - infracost/infracost:
      #     path: terraform
      #     usage_file: infracost-usage.yml
      - infracost/infracost:
          context: aidock-platform-context-dev
          path: /workspace/.terraform/tfplan.json
          requires:
            - plan
          pre-steps:
            - attach_workspace:
                at: workspace
            - run:
                command: ls -lah /workspace/.terraform/
